In [58]:
# Import Packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

In [59]:
# Load the dataset
df = pd.read_csv('tech_companies_salary.csv')
# Display the first few rows of the dataframe
print(df.head())
# Display summary information about the dataframe
df.info

            timestamp    company level                         title  \
0    06-07-2017 11:33     Oracle    L3               Product Manager
1    06-10-2017 17:11       eBay  SE 2             Software Engineer
2    06-11-2017 14:53     Amazon    L7               Product Manager
3   6/17/2017 0:23:14      Apple    M1  Software Engineering Manager
4  6/20/2017 10:58:51  Microsoft    60             Software Engineer

   totalyearlycompensation           location  yearsofexperience  \
0                   127000   Redwood City, CA                1.5
1                   100000  San Francisco, CA                5.0
2                   310000        Seattle, WA                8.0
3                   372000      Sunnyvale, CA                7.0
4                   157000  Mountain View, CA                5.0

   yearsatcompany  tag  basesalary  ...  Doctorate_Degree  Highschool  \
0             1.5  NaN      107000  ...                 0           0
1             3.0  NaN           0  ...                 0           0
2             0.0  NaN      155000  ...                 0           0
3             5.0  NaN      157000  ...                 0           0
4             3.0  NaN           0  ...                 0           0

  Some_College Race_Asian  Race_White  Race_Two_Or_More  Race_Black  \
0            0          0           0                 0           0
1            0          0           0                 0           0
2            0          0           0                 0           0
3            0          0           0                 0           0
4            0          0           0                 0           0

   Race_Hispanic  Race  Education
0              0   NaN        NaN
1              0   NaN        NaN
2              0   NaN        NaN
3              0   NaN        NaN
4              0   NaN        NaN

[5 rows x 29 columns]

<bound method DataFrame.info of                 timestamp     company     level                         title  \
0        06-07-2017 11:33      Oracle        L3               Product Manager
1        06-10-2017 17:11        eBay      SE 2             Software Engineer
2        06-11-2017 14:53      Amazon        L7               Product Manager
3       6/17/2017 0:23:14       Apple        M1  Software Engineering Manager
4      6/20/2017 10:58:51   Microsoft        60             Software Engineer
...                   ...         ...       ...                           ...
62637    09-09-2018 11:52      Google        T4             Software Engineer
62638   9/13/2018 8:23:32   Microsoft        62             Software Engineer
62639  9/13/2018 14:35:59        MSFT        63             Software Engineer
62640  9/16/2018 16:10:35  Salesforce  Lead MTS             Software Engineer
62641   1/29/2019 5:12:59       apple      ict3             Software Engineer

       totalyearlycompensation           location  yearsofexperience  \
0                       127000   Redwood City, CA                1.5
1                       100000  San Francisco, CA                5.0
2                       310000        Seattle, WA                8.0
3                       372000      Sunnyvale, CA                7.0
4                       157000  Mountain View, CA                5.0
...                        ...                ...                ...
62637                   327000        Seattle, WA               10.0
62638                   237000        Redmond, WA                2.0
62639                   220000        Seattle, WA               14.0
62640                   280000  San Francisco, CA                8.0
62641                   200000      Sunnyvale, CA                0.0

       yearsatcompany                             tag  basesalary  ...  \
0                 1.5                             NaN      107000  ...
1                 3.0                             NaN           0  ...
2                 0.0                             NaN      155000  ...
3                 5.0                             NaN      157000  ...
4                 3.0                             NaN           0  ...
...               ...                             ...         ...  ...
62637             1.0  Distributed Systems (Back-End)      155000  ...
62638             2.0                      Full Stack      146900  ...
62639            12.0                      Full Stack      157000  ...
62640             4.0                             iOS      194688  ...
62641             0.0                         ML / AI      155000  ...

       Doctorate_Degree  Highschool Some_College Race_Asian  Race_White  \
0                     0           0            0          0           0
1                     0           0            0          0           0
2                     0           0            0          0           0
3                     0           0            0          0           0
4                     0           0            0          0           0
...                 ...         ...          ...        ...         ...
62637                 0           0            0          0           0
62638                 0           0            0          0           0
62639                 0           0            0          0           0
62640                 0           0            0          0           0
62641                 0           0            0          0           0

       Race_Two_Or_More  Race_Black  Race_Hispanic  Race  Education
0                     0           0              0   NaN        NaN
1                     0           0              0   NaN        NaN
2                     0           0              0   NaN        NaN
3                     0           0              0   NaN        NaN
4                     0           0              0   NaN        NaN
...                 ...         ...            ...   ...        ...
62637                 0           0              0   NaN        NaN
62638                 0           0              0   NaN        NaN
62639                 0           0              0   NaN        NaN
62640                 0           0              0   NaN        NaN
62641                 0           0              0   NaN        NaN

[62642 rows x 29 columns]>

In [60]:
# Number of null values in each column
df.isna().sum()

timestamp                      0
company                        5
level                        123
title                          0
totalyearlycompensation        0
location                       0
yearsofexperience              0
yearsatcompany                 0
tag                          870
basesalary                     0
stockgrantvalue                0
bonus                          0
gender                     19540
otherdetails               22508
cityid                         0
dmaid                          2
rowNumber                      0
Masters_Degree                 0
Bachelors_Degree               0
Doctorate_Degree               0
Highschool                     0
Some_College                   0
Race_Asian                     0
Race_White                     0
Race_Two_Or_More               0
Race_Black                     0
Race_Hispanic                  0
Race                       40215
Education                  32272
dtype: int64

# *** Review data dropped to see if column with null values can be included based on variables used in model (probably tag and level) ***

In [61]:
# Remove rows with null values in subset columns
df = df.dropna(subset=['gender', 'Education', 'company', 'Race', 'tag', 'level'])
# Verify removal
print(df.isna().sum())

timestamp                  0
company                    0
level                      0
title                      0
totalyearlycompensation    0
location                   0
yearsofexperience          0
yearsatcompany             0
tag                        0
basesalary                 0
stockgrantvalue            0
bonus                      0
gender                     0
otherdetails               0
cityid                     0
dmaid                      0
rowNumber                  0
Masters_Degree             0
Bachelors_Degree           0
Doctorate_Degree           0
Highschool                 0
Some_College               0
Race_Asian                 0
Race_White                 0
Race_Two_Or_More           0
Race_Black                 0
Race_Hispanic              0
Race                       0
Education                  0
dtype: int64

In [62]:
df.drop_duplicates(inplace=True)

C:\Users\mattb\AppData\Local\Temp\ipykernel_5136\3006716147.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)

In [63]:
df.size

623935

In [64]:
df.describe()

,totalyearlycompensation,yearsofexperience,yearsatcompany,basesalary,stockgrantvalue,bonus,cityid,dmaid,rowNumber,Masters_Degree,Bachelors_Degree,Doctorate_Degree,Highschool,Some_College,Race_Asian,Race_White,Race_Two_Or_More,Race_Black,Race_Hispanic
count,2.151500e+04,21515.000000,21515.000000,21515.000000,21515.000000,21515.000000,21515.000000,21515.000000,21515.000000,21515.000000,21515.000000,21515.000000,21515.000000,21515.000000,21515.000000,21515.000000,21515.000000,21515.000000,21515.000000
mean,1.979508e+05,7.127167,2.706995,133894.538694,44974.392424,18401.301418,10177.354218,561.242436,59207.188891,0.421055,0.506577,0.042854,0.013944,0.015710,0.528887,0.355612,0.035417,0.030769,0.049361
std,1.331313e+05,5.848876,3.328438,57231.645682,72523.732291,24802.564405,7677.552448,315.744730,14561.633489,0.493740,0.499968,0.202532,0.117260,0.124354,0.499176,0.478710,0.184836,0.172696,0.216625
min,1.000000e+04,0.000000,0.000000,4000.000000,0.000000,0.000000,10.000000,0.000000,21208.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.190000e+05,3.000000,0.000000,100000.000000,0.000000,3000.000000,7322.000000,501.000000,47070.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.740000e+05,6.000000,2.000000,135000.000000,20000.000000,13000.000000,8198.000000,751.000000,59849.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
75%,2.450000e+05,10.000000,4.000000,165000.000000,55000.000000,25000.000000,11521.000000,807.000000,71599.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000
max,4.980000e+06,45.000000,40.000000,900000.000000,954000.000000,900000.000000,47926.000000,881.000000,83875.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [65]:
df = df[['totalyearlycompensation', 'basesalary', 'bonus', 'company', 'cityid', 'location', 'level', 'title', 'tag', 'yearsofexperience',
        'yearsatcompany', 'stockgrantvalue', 'dmaid', 'rowNumber', 'Race', 'Education']]
df.head(20)

,totalyearlycompensation,basesalary,bonus,company,cityid,location,level,title,tag,yearsofexperience,yearsatcompany,stockgrantvalue,dmaid,rowNumber,Race,Education
15710,400000,210000,45000.0,Google,7472,"Sunnyvale, CA",L6,Software Engineer,Distributed Systems (Back-End),5.0,5.0,145000.0,807.0,21208,Asian,PhD
23532,136000,124000,11000.0,Microsoft,11521,"Redmond, WA",61,Software Engineer,DevOps,3.0,2.0,1000.0,819.0,32237,Two Or More,Bachelor's Degree
23533,337000,177000,36000.0,Google,7413,"San Bruno, CA",L5,Software Engineer,Full Stack,6.0,6.0,125000.0,807.0,32239,Asian,Bachelor's Degree
23534,222000,164000,20000.0,Microsoft,11527,"Seattle, WA",62,Software Engineer,API Development (Back-End),4.0,4.0,38000.0,819.0,32240,Asian,Master's Degree
23535,187000,165000,0.0,Blend,7419,"San Francisco, CA",IC3,Software Engineer,Full Stack,5.0,0.0,22000.0,807.0,32241,White,Bachelor's Degree
23537,310000,160000,0.0,Amazon,11527,"Seattle, WA",L6,Software Engineer,ML / AI,15.0,3.0,150000.0,819.0,32243,Asian,Bachelor's Degree
23538,113000,103000,10000.0,Chevron,11109,"Houston, TX",PSG 20,Software Engineer,DevOps,3.0,3.0,0.0,618.0,32244,Hispanic,Bachelor's Degree
23540,620000,160000,0.0,Amazon,11527,"Seattle, WA",L7,Software Engineering Manager,Full Stack,19.0,7.0,460000.0,819.0,32247,Asian,Bachelor's Degree
23541,98000,78000,0.0,Shopify,1206,"Toronto, ON, Canada",L6,Software Engineer,Web Development (Front-End),9.0,4.0,20000.0,0.0,32248,Asian,Bachelor's Degree
23543,180000,130000,20000.0,Apple,1320,"Vancouver, BC, Canada",ICT3,Software Engineer,ML / AI,1.0,1.0,30000.0,0.0,32250,Asian,Bachelor's Degree
23544,212000,140000,10000.0,Square,7419,"San Francisco, CA",Level 4,Software Engineer,Full Stack,5.0,1.0,62000.0,807.0,32251,Black,Some College
23545,210000,150000,0.0,Amazon,11527,"Seattle, WA",L5,Software Engineer,Site Reliability (SRE),4.0,1.0,60000.0,819.0,32252,Hispanic,Highschool
23546,68000,45000,7000.0,Salesforce,4058,"Bangalore, KA, India",Senior MTS,Software Engineer,Site Reliability (SRE),8.0,1.0,16000.0,0.0,32254,Asian,Master's Degree
23548,142000,112000,26000.0,Amazon,7053,"Tempe, AZ",L4,Software Engineer,Full Stack,0.0,0.0,4000.0,753.0,32257,Asian,Master's Degree
23549,129000,114000,0.0,Intel,7434,"Santa Clara, CA",Grade 5,Software Engineer,Performance,6.0,4.0,15000.0,807.0,32259,Two Or More,Master's Degree
23550,242000,167000,0.0,Facebook,7300,"Menlo Park, CA",E4,Software Engineer,ML / AI,2.0,2.0,75000.0,807.0,32260,White,Master's Degree
23552,215000,155000,15000.0,PayPal,10965,"Austin, TX",T25,Software Engineer,iOS,6.0,0.0,45000.0,635.0,32264,Asian,Master's Degree
23553,365000,187000,38000.0,Twitter,10182,"New York, NY",Senior SWE,Software Engineer,iOS,10.0,6.0,140000.0,501.0,32265,White,Highschool
23554,135000,110000,10000.0,Microsoft,11527,"Seattle, WA",59,Software Engineer,Networking,1.0,0.0,14000.0,819.0,32268,Hispanic,Bachelor's Degree
23555,173000,153000,10000.0,Microsoft,11521,"Redmond, WA",62,Software Engineer,ML / AI,10.0,2.0,9000.0,819.0,32269,Asian,Bachelor's Degree

In [66]:
# Method to split the location column into city and state columns.
# locations with more than 2 strings delimited by ',' will be set to null values
#     these correspond to locations outside of the US
def split_location(loc):
    location = loc.split(', ')  
    if len(location) == 2:
        city = location[0]
        state = location[1]
    else:
        city = None
        state = None
    return pd.Series([city, state])

df[['City', 'State']] = df['location'].apply(split_location)
df.head()

,totalyearlycompensation,basesalary,bonus,company,cityid,location,level,title,tag,yearsofexperience,yearsatcompany,stockgrantvalue,dmaid,rowNumber,Race,Education,City,State
15710,400000,210000,45000.0,Google,7472,"Sunnyvale, CA",L6,Software Engineer,Distributed Systems (Back-End),5.0,5.0,145000.0,807.0,21208,Asian,PhD,Sunnyvale,CA
23532,136000,124000,11000.0,Microsoft,11521,"Redmond, WA",61,Software Engineer,DevOps,3.0,2.0,1000.0,819.0,32237,Two Or More,Bachelor's Degree,Redmond,WA
23533,337000,177000,36000.0,Google,7413,"San Bruno, CA",L5,Software Engineer,Full Stack,6.0,6.0,125000.0,807.0,32239,Asian,Bachelor's Degree,San Bruno,CA
23534,222000,164000,20000.0,Microsoft,11527,"Seattle, WA",62,Software Engineer,API Development (Back-End),4.0,4.0,38000.0,819.0,32240,Asian,Master's Degree,Seattle,WA
23535,187000,165000,0.0,Blend,7419,"San Francisco, CA",IC3,Software Engineer,Full Stack,5.0,0.0,22000.0,807.0,32241,White,Bachelor's Degree,San Francisco,CA

In [67]:
df = df[['totalyearlycompensation', 'basesalary', 'bonus', 'company', 'cityid', 'location', 'State', 'City', 'level', 'title', 'tag', 'yearsofexperience',
        'yearsatcompany', 'stockgrantvalue', 'dmaid', 'rowNumber', 'Race', 'Education']]
df.head(50)

,totalyearlycompensation,basesalary,bonus,company,cityid,location,State,City,level,title,tag,yearsofexperience,yearsatcompany,stockgrantvalue,dmaid,rowNumber,Race,Education
15710,400000,210000,45000.0,Google,7472,"Sunnyvale, CA",CA,Sunnyvale,L6,Software Engineer,Distributed Systems (Back-End),5.0,5.0,145000.0,807.0,21208,Asian,PhD
23532,136000,124000,11000.0,Microsoft,11521,"Redmond, WA",WA,Redmond,61,Software Engineer,DevOps,3.0,2.0,1000.0,819.0,32237,Two Or More,Bachelor's Degree
23533,337000,177000,36000.0,Google,7413,"San Bruno, CA",CA,San Bruno,L5,Software Engineer,Full Stack,6.0,6.0,125000.0,807.0,32239,Asian,Bachelor's Degree
23534,222000,164000,20000.0,Microsoft,11527,"Seattle, WA",WA,Seattle,62,Software Engineer,API Development (Back-End),4.0,4.0,38000.0,819.0,32240,Asian,Master's Degree
23535,187000,165000,0.0,Blend,7419,"San Francisco, CA",CA,San Francisco,IC3,Software Engineer,Full Stack,5.0,0.0,22000.0,807.0,32241,White,Bachelor's Degree
23537,310000,160000,0.0,Amazon,11527,"Seattle, WA",WA,Seattle,L6,Software Engineer,ML / AI,15.0,3.0,150000.0,819.0,32243,Asian,Bachelor's Degree
23538,113000,103000,10000.0,Chevron,11109,"Houston, TX",TX,Houston,PSG 20,Software Engineer,DevOps,3.0,3.0,0.0,618.0,32244,Hispanic,Bachelor's Degree
23540,620000,160000,0.0,Amazon,11527,"Seattle, WA",WA,Seattle,L7,Software Engineering Manager,Full Stack,19.0,7.0,460000.0,819.0,32247,Asian,Bachelor's Degree
23541,98000,78000,0.0,Shopify,1206,"Toronto, ON, Canada",None,None,L6,Software Engineer,Web Development (Front-End),9.0,4.0,20000.0,0.0,32248,Asian,Bachelor's Degree
23543,180000,130000,20000.0,Apple,1320,"Vancouver, BC, Canada",None,None,ICT3,Software Engineer,ML / AI,1.0,1.0,30000.0,0.0,32250,Asian,Bachelor's Degree
23544,212000,140000,10000.0,Square,7419,"San Francisco, CA",CA,San Francisco,Level 4,Software Engineer,Full Stack,5.0,1.0,62000.0,807.0,32251,Black,Some College
23545,210000,150000,0.0,Amazon,11527,"Seattle, WA",WA,Seattle,L5,Software Engineer,Site Reliability (SRE),4.0,1.0,60000.0,819.0,32252,Hispanic,Highschool
23546,68000,45000,7000.0,Salesforce,4058,"Bangalore, KA, India",None,None,Senior MTS,Software Engineer,Site Reliability (SRE),8.0,1.0,16000.0,0.0,32254,Asian,Master's Degree
23548,142000,112000,26000.0,Amazon,7053,"Tempe, AZ",AZ,Tempe,L4,Software Engineer,Full Stack,0.0,0.0,4000.0,753.0,32257,Asian,Master's Degree
23549,129000,114000,0.0,Intel,7434,"Santa Clara, CA",CA,Santa Clara,Grade 5,Software Engineer,Performance,6.0,4.0,15000.0,807.0,32259,Two Or More,Master's Degree
23550,242000,167000,0.0,Facebook,7300,"Menlo Park, CA",CA,Menlo Park,E4,Software Engineer,ML / AI,2.0,2.0,75000.0,807.0,32260,White,Master's Degree
23552,215000,155000,15000.0,PayPal,10965,"Austin, TX",TX,Austin,T25,Software Engineer,iOS,6.0,0.0,45000.0,635.0,32264,Asian,Master's Degree
23553,365000,187000,38000.0,Twitter,10182,"New York, NY",NY,New York,Senior SWE,Software Engineer,iOS,10.0,6.0,140000.0,501.0,32265,White,Highschool
23554,135000,110000,10000.0,Microsoft,11527,"Seattle, WA",WA,Seattle,59,Software Engineer,Networking,1.0,0.0,14000.0,819.0,32268,Hispanic,Bachelor's Degree
23555,173000,153000,10000.0,Microsoft,11521,"Redmond, WA",WA,Redmond,62,Software Engineer,ML / AI,10.0,2.0,9000.0,819.0,32269,Asian,Bachelor's Degree
23556,134000,130000,0.0,Intel,7422,"San Jose, CA",CA,San Jose,Staff Engineer,Hardware Engineer,Application Engineer,6.0,6.0,4000.0,807.0,32270,Asian,Master's Degree
23557,121000,111000,10000.0,Charles Schwab,10965,"Austin, TX",TX,Austin,III,Software Engineer,DevOps,9.0,4.0,0.0,635.0,32271,Hispanic,Master's Degree
23558,328000,215000,50000.0,Microsoft,7419,"San Francisco, CA",CA,San Francisco,64,Software Engineer,Mixed reality,12.0,0.0,63000.0,807.0,32272,Asian,Bachelor's Degree
23559,300000,160000,40000.0,Tanium,8198,"Chicago, IL",IL,Chicago,Senior,Software Engineer,Full Stack,15.0,0.0,100000.0,602.0,32273,White,Master's Degree
23562,309000,201000,40000.0,Facebook,7300,"Menlo Park, CA",CA,Menlo Park,M1,Software Engineering Manager,DevOps,14.0,2.0,68000.0,807.0,32277,Two Or More,Master's Degree
23564,46000,27000,4000.0,Google,4058,"Bangalore, KA, India",None,None,L3,Software Engineer,Distributed Systems (Back-End),2.0,0.0,12000.0,0.0,32280,Asian,Bachelor's Degree
23565,493000,215000,54000.0,ByteDance,7322,"Mountain View, CA",CA,Mountain View,03-Jan,Software Engineer,Full Stack,10.0,0.0,225000.0,807.0,32281,Asian,Master's Degree
23566,190000,180000,10000.0,Ticketmaster,7275,"Los Angeles, CA",CA,Los Angeles,Lead Engineer,Software Engineer,Distributed Systems (Back-End),10.0,6.0,0.0,803.0,32282,Asian,Master's Degree
23567,255000,160000,16000.0,Facebook,7300,"Menlo Park, CA",CA,Menlo Park,E4,Software Engineer,ML / AI,6.0,2.0,75000.0,807.0,32283,Asian,Master's Degree
23568,260000,210000,0.0,GoDaddy,11527,"Seattle, WA",WA,Seattle,Principal,Software Engineer,Full Stack,15.0,2.0,50000.0,819.0,32284,White,Bachelor's Degree
23574,50000,36000,0.0,Amazon,16743,"Gurgaon, HR, India",None,None,L5,Software Engineer,Full Stack,3.0,3.0,14000.0,0.0,32294,Asian,Bachelor's Degree
23575,74000,53000,0.0,Salesforce,6453,"Hyderabad, AP, India",None,None,SMTS,Software Engineer,Full Stack,7.0,0.0,21000.0,0.0,32295,Asian,Master's Degree
23577,30000,27000,2000.0,BrowserStack,6457,"Mumbai, MH, India",None,None,Software Engineer,Software Engineer,Backend,2.0,2.0,1000.0,0.0,32299,Asian,Bachelor's Degree
23578,275000,170000,25000.0,Smartsheet,8816,"Boston, MA",MA,Boston,Sde4,Software Engineer,Full Stack,10.0,3.0,75000.0,506.0,32301,White,Master's Degree
23579,287000,250000,37000.0,Citi,10182,"New York, NY",NY,New York,Senior Vice President,Software Engineer,Distributed Systems (Back-End),19.0,3.0,0.0,501.0,32302,Asian,Master's Degree
23580,144000,126000,18000.0,Johnson and Johnson,10182,"New York, NY",NY,New York,30,Product Designer,Design,7.0,2.0,0.0,501.0,32303,Asian,Master's Degree
23583,266000,246000,20000.0,KPMG,10965,"Austin, TX",TX,Austin,Director,Management Consultant,Cloud,14.0,3.0,0.0,635.0,32306,Asian,Master's Degree
23585,309000,220000,33000.0,Apple,7158,"Cupertino, CA",CA,Cupertino,IC5,Product Manager,Video,10.0,1.0,56000.0,807.0,32308,Hispanic,Bachelor's Degree
23586,189000,135000,49000.0,Amazon,11527,"Seattle, WA",WA,Seattle,L4,Software Engineer,Android,2.0,0.0,6000.0,819.0,32310,Asian,Bachelor's Degree
23588,347000,150000,0.0,Amazon,11527,"Seattle, WA",WA,Seattle,L6,Product Manager,Cloud,18.0,3.0,193000.0,819.0,32313,Asian,Master's Degree
23590,74000,74000,0.0,EY,16743,"Gurgaon, HR, India",None,None,Senior Manager,Solution Architect,Full Stack,17.0,0.0,0.0,0.0,32315,Asian,Bachelor's Degree
23591,550000,160000,0.0,Amazon,8816,"Boston, MA",MA,Boston,L7,Software Engineer,Distributed Systems (Back-End),10.0,6.0,390000.0,506.0,32316,White,PhD
23596,232000,180000,42000.0,AMD,7434,"Santa Clara, CA",CA,Santa Clara,MTS,Software Engineer,ML / AI,5.0,0.0,10000.0,807.0,32324,Two Or More,PhD
23598,135000,120000,15000.0,Tiaa,9594,"Charlotte, NC",NC,Charlotte,Sr Developer,Software Engineer,API Development (Back-End),6.0,6.0,0.0,517.0,32327,White,Bachelor's Degree
23601,272000,165000,17000.0,Facebook,10182,"New York, NY",NY,New York,IC4,Software Engineer,Generalist,2.0,0.0,90000.0,501.0,32332,Asian,Master's Degree
23603,100000,90000,10000.0,EY,10182,"New York, NY",NY,New York,Staff,Management Consultant,consulting,0.0,0.0,0.0,501.0,32334,White,Bachelor's Degree
23604,800000,250000,0.0,MongoDB,10182,"New York, NY",NY,New York,Staff Software Engineer,Software Engineer,Distributed Systems (Back-End),15.0,8.0,550000.0,501.0,32336,White,Bachelor's Degree
23605,272000,165000,17000.0,Facebook,11527,"Seattle, WA",WA,Seattle,E4,Software Engineer,VR,5.0,0.0,90000.0,819.0,32337,White,Bachelor's Degree
23606,162000,130000,0.0,Apple,7434,"Santa Clara, CA",CA,Santa Clara,ICT2,Software Engineer,ML / AI,0.0,0.0,32000.0,807.0,32338,White,Bachelor's Degree
23607,99000,66000,0.0,Shopify,5906,"Ottawa, ON, Canada",None,None,L4,Software Engineer,Web Development (Front-End),3.0,1.0,33000.0,0.0,32339,White,Bachelor's Degree

In [68]:
df.State.unique()

array(['CA', 'WA', 'TX', None, 'AZ', 'NY', 'IL', 'MA', 'NC', 'VA', 'CO',
       'FL', 'WI', 'DC', 'OR', 'MI', 'MN', 'MO', 'PA', 'UT', 'NJ', 'TN',
       'LA', 'GA', 'AR', 'IA', 'OH', 'MD', 'IN', 'MT', 'RI', 'DE', 'OK',
       'NV', 'CT', 'AL', 'SC', 'KS', 'KY', 'WV', 'MS', 'ID', 'NE', 'HI',
       'NH', 'NM', 'ND', 'VT', 'WY', 'ME'], dtype=object)

In [69]:
# Remove rows with null values in State column
df = df.dropna(subset='State')
# Verify removal
print(df.isna().sum())

totalyearlycompensation    0
basesalary                 0
bonus                      0
company                    0
cityid                     0
location                   0
State                      0
City                       0
level                      0
title                      0
tag                        0
yearsofexperience          0
yearsatcompany             0
stockgrantvalue            0
dmaid                      0
rowNumber                  0
Race                       0
Education                  0
dtype: int64

In [70]:
df.head(50)

,totalyearlycompensation,basesalary,bonus,company,cityid,location,State,City,level,title,tag,yearsofexperience,yearsatcompany,stockgrantvalue,dmaid,rowNumber,Race,Education
15710,400000,210000,45000.0,Google,7472,"Sunnyvale, CA",CA,Sunnyvale,L6,Software Engineer,Distributed Systems (Back-End),5.0,5.0,145000.0,807.0,21208,Asian,PhD
23532,136000,124000,11000.0,Microsoft,11521,"Redmond, WA",WA,Redmond,61,Software Engineer,DevOps,3.0,2.0,1000.0,819.0,32237,Two Or More,Bachelor's Degree
23533,337000,177000,36000.0,Google,7413,"San Bruno, CA",CA,San Bruno,L5,Software Engineer,Full Stack,6.0,6.0,125000.0,807.0,32239,Asian,Bachelor's Degree
23534,222000,164000,20000.0,Microsoft,11527,"Seattle, WA",WA,Seattle,62,Software Engineer,API Development (Back-End),4.0,4.0,38000.0,819.0,32240,Asian,Master's Degree
23535,187000,165000,0.0,Blend,7419,"San Francisco, CA",CA,San Francisco,IC3,Software Engineer,Full Stack,5.0,0.0,22000.0,807.0,32241,White,Bachelor's Degree
23537,310000,160000,0.0,Amazon,11527,"Seattle, WA",WA,Seattle,L6,Software Engineer,ML / AI,15.0,3.0,150000.0,819.0,32243,Asian,Bachelor's Degree
23538,113000,103000,10000.0,Chevron,11109,"Houston, TX",TX,Houston,PSG 20,Software Engineer,DevOps,3.0,3.0,0.0,618.0,32244,Hispanic,Bachelor's Degree
23540,620000,160000,0.0,Amazon,11527,"Seattle, WA",WA,Seattle,L7,Software Engineering Manager,Full Stack,19.0,7.0,460000.0,819.0,32247,Asian,Bachelor's Degree
23544,212000,140000,10000.0,Square,7419,"San Francisco, CA",CA,San Francisco,Level 4,Software Engineer,Full Stack,5.0,1.0,62000.0,807.0,32251,Black,Some College
23545,210000,150000,0.0,Amazon,11527,"Seattle, WA",WA,Seattle,L5,Software Engineer,Site Reliability (SRE),4.0,1.0,60000.0,819.0,32252,Hispanic,Highschool
23548,142000,112000,26000.0,Amazon,7053,"Tempe, AZ",AZ,Tempe,L4,Software Engineer,Full Stack,0.0,0.0,4000.0,753.0,32257,Asian,Master's Degree
23549,129000,114000,0.0,Intel,7434,"Santa Clara, CA",CA,Santa Clara,Grade 5,Software Engineer,Performance,6.0,4.0,15000.0,807.0,32259,Two Or More,Master's Degree
23550,242000,167000,0.0,Facebook,7300,"Menlo Park, CA",CA,Menlo Park,E4,Software Engineer,ML / AI,2.0,2.0,75000.0,807.0,32260,White,Master's Degree
23552,215000,155000,15000.0,PayPal,10965,"Austin, TX",TX,Austin,T25,Software Engineer,iOS,6.0,0.0,45000.0,635.0,32264,Asian,Master's Degree
23553,365000,187000,38000.0,Twitter,10182,"New York, NY",NY,New York,Senior SWE,Software Engineer,iOS,10.0,6.0,140000.0,501.0,32265,White,Highschool
23554,135000,110000,10000.0,Microsoft,11527,"Seattle, WA",WA,Seattle,59,Software Engineer,Networking,1.0,0.0,14000.0,819.0,32268,Hispanic,Bachelor's Degree
23555,173000,153000,10000.0,Microsoft,11521,"Redmond, WA",WA,Redmond,62,Software Engineer,ML / AI,10.0,2.0,9000.0,819.0,32269,Asian,Bachelor's Degree
23556,134000,130000,0.0,Intel,7422,"San Jose, CA",CA,San Jose,Staff Engineer,Hardware Engineer,Application Engineer,6.0,6.0,4000.0,807.0,32270,Asian,Master's Degree
23557,121000,111000,10000.0,Charles Schwab,10965,"Austin, TX",TX,Austin,III,Software Engineer,DevOps,9.0,4.0,0.0,635.0,32271,Hispanic,Master's Degree
23558,328000,215000,50000.0,Microsoft,7419,"San Francisco, CA",CA,San Francisco,64,Software Engineer,Mixed reality,12.0,0.0,63000.0,807.0,32272,Asian,Bachelor's Degree
23559,300000,160000,40000.0,Tanium,8198,"Chicago, IL",IL,Chicago,Senior,Software Engineer,Full Stack,15.0,0.0,100000.0,602.0,32273,White,Master's Degree
23562,309000,201000,40000.0,Facebook,7300,"Menlo Park, CA",CA,Menlo Park,M1,Software Engineering Manager,DevOps,14.0,2.0,68000.0,807.0,32277,Two Or More,Master's Degree
23565,493000,215000,54000.0,ByteDance,7322,"Mountain View, CA",CA,Mountain View,03-Jan,Software Engineer,Full Stack,10.0,0.0,225000.0,807.0,32281,Asian,Master's Degree
23566,190000,180000,10000.0,Ticketmaster,7275,"Los Angeles, CA",CA,Los Angeles,Lead Engineer,Software Engineer,Distributed Systems (Back-End),10.0,6.0,0.0,803.0,32282,Asian,Master's Degree
23567,255000,160000,16000.0,Facebook,7300,"Menlo Park, CA",CA,Menlo Park,E4,Software Engineer,ML / AI,6.0,2.0,75000.0,807.0,32283,Asian,Master's Degree
23568,260000,210000,0.0,GoDaddy,11527,"Seattle, WA",WA,Seattle,Principal,Software Engineer,Full Stack,15.0,2.0,50000.0,819.0,32284,White,Bachelor's Degree
23578,275000,170000,25000.0,Smartsheet,8816,"Boston, MA",MA,Boston,Sde4,Software Engineer,Full Stack,10.0,3.0,75000.0,506.0,32301,White,Master's Degree
23579,287000,250000,37000.0,Citi,10182,"New York, NY",NY,New York,Senior Vice President,Software Engineer,Distributed Systems (Back-End),19.0,3.0,0.0,501.0,32302,Asian,Master's Degree
23580,144000,126000,18000.0,Johnson and Johnson,10182,"New York, NY",NY,New York,30,Product Designer,Design,7.0,2.0,0.0,501.0,32303,Asian,Master's Degree
23583,266000,246000,20000.0,KPMG,10965,"Austin, TX",TX,Austin,Director,Management Consultant,Cloud,14.0,3.0,0.0,635.0,32306,Asian,Master's Degree
23585,309000,220000,33000.0,Apple,7158,"Cupertino, CA",CA,Cupertino,IC5,Product Manager,Video,10.0,1.0,56000.0,807.0,32308,Hispanic,Bachelor's Degree
23586,189000,135000,49000.0,Amazon,11527,"Seattle, WA",WA,Seattle,L4,Software Engineer,Android,2.0,0.0,6000.0,819.0,32310,Asian,Bachelor's Degree
23588,347000,150000,0.0,Amazon,11527,"Seattle, WA",WA,Seattle,L6,Product Manager,Cloud,18.0,3.0,193000.0,819.0,32313,Asian,Master's Degree
23591,550000,160000,0.0,Amazon,8816,"Boston, MA",MA,Boston,L7,Software Engineer,Distributed Systems (Back-End),10.0,6.0,390000.0,506.0,32316,White,PhD
23596,232000,180000,42000.0,AMD,7434,"Santa Clara, CA",CA,Santa Clara,MTS,Software Engineer,ML / AI,5.0,0.0,10000.0,807.0,32324,Two Or More,PhD
23598,135000,120000,15000.0,Tiaa,9594,"Charlotte, NC",NC,Charlotte,Sr Developer,Software Engineer,API Development (Back-End),6.0,6.0,0.0,517.0,32327,White,Bachelor's Degree
23601,272000,165000,17000.0,Facebook,10182,"New York, NY",NY,New York,IC4,Software Engineer,Generalist,2.0,0.0,90000.0,501.0,32332,Asian,Master's Degree
23603,100000,90000,10000.0,EY,10182,"New York, NY",NY,New York,Staff,Management Consultant,consulting,0.0,0.0,0.0,501.0,32334,White,Bachelor's Degree
23604,800000,250000,0.0,MongoDB,10182,"New York, NY",NY,New York,Staff Software Engineer,Software Engineer,Distributed Systems (Back-End),15.0,8.0,550000.0,501.0,32336,White,Bachelor's Degree
23605,272000,165000,17000.0,Facebook,11527,"Seattle, WA",WA,Seattle,E4,Software Engineer,VR,5.0,0.0,90000.0,819.0,32337,White,Bachelor's Degree
23606,162000,130000,0.0,Apple,7434,"Santa Clara, CA",CA,Santa Clara,ICT2,Software Engineer,ML / AI,0.0,0.0,32000.0,807.0,32338,White,Bachelor's Degree
23608,190000,127000,13000.0,PayPal,7422,"San Jose, CA",CA,San Jose,T24,Software Engineer,Distributed Systems (Back-End),4.0,4.0,50000.0,807.0,32340,Asian,Bachelor's Degree
23609,252000,160000,10000.0,Amazon,11342,"Arlington, VA",VA,Arlington,L5,Software Engineer,Full Stack,4.0,0.0,82000.0,511.0,32342,Asian,Bachelor's Degree
23611,230000,185000,41000.0,SAP,7351,"Palo Alto, CA",CA,Palo Alto,Product Manager,Product Manager,ERP,20.0,15.0,4000.0,807.0,32345,White,Master's Degree
23613,181000,180000,0.0,Amazon,7141,"Claremont, CA",CA,Claremont,Senior SDE,Solution Architect,DevOps,10.0,2.0,1000.0,803.0,32348,Black,Bachelor's Degree
23614,381000,198000,24000.0,Flexport,7419,"San Francisco, CA",CA,San Francisco,Staff Engineer,Software Engineer,Full Stack,5.0,5.0,160000.0,807.0,32349,White,Master's Degree
23617,176000,120000,20000.0,Oracle,7536,"Broomfield, CO",CO,Broomfield,1,Software Engineer,iOS,0.0,0.0,36000.0,751.0,32353,White,Bachelor's Degree
23618,162000,140000,16000.0,Expedia,11527,"Seattle, WA",WA,Seattle,SDE II,Software Engineer,API Development (Back-End),5.0,2.0,7000.0,819.0,32354,Asian,Master's Degree
23620,289000,163000,24000.0,Google,7322,"Mountain View, CA",CA,Mountain View,L4,Software Engineer,Distributed Systems (Back-End),6.0,1.0,100000.0,807.0,32356,Asian,Master's Degree
23622,334000,191000,29000.0,Facebook,7300,"Menlo Park, CA",CA,Menlo Park,E5,Software Engineer,Full Stack,11.0,3.0,114000.0,807.0,32358,Hispanic,Master's Degree

In [71]:
df.State.unique()

array(['CA', 'WA', 'TX', 'AZ', 'NY', 'IL', 'MA', 'NC', 'VA', 'CO', 'FL',
       'WI', 'DC', 'OR', 'MI', 'MN', 'MO', 'PA', 'UT', 'NJ', 'TN', 'LA',
       'GA', 'AR', 'IA', 'OH', 'MD', 'IN', 'MT', 'RI', 'DE', 'OK', 'NV',
       'CT', 'AL', 'SC', 'KS', 'KY', 'WV', 'MS', 'ID', 'NE', 'HI', 'NH',
       'NM', 'ND', 'VT', 'WY', 'ME'], dtype=object)